export declare enum OrderTokenType {
    march_minusOne = 0,
    march_zero = 1,
    march_special = 2,
    defend_0 = 3,
    defend_1 = 4,
    defend_special = 5,
    support_0 = 6,
    support_1 = 7,
    support_special = 8,
    raid_0 = 9,
    raid_1 = 10,
    raid_special = 11,
    consolidatePower_0 = 12,
    consolidatePower_1 = 13,
    consolidatePower_special = 14,
}
